when:
  - event: [ push, pull_request, tag ]

steps:
  - name: tags
    image: ghcr.io/dvjn/woodpecker-docker-tags-plugin
    settings:
      tags: |
        edge -v latest
        edge -b main -v main
        edge -b dev -v dev
        edge -b next -v next
        cron
        pr
        semver --format {{major}}
        semver --format {{major}}.{{minor}}
        semver --format {{version}}
        sha
  - name: build
    image: quay.io/woodpeckerci/plugin-kaniko
    settings:
      registry: reg.zyner.org
      repo: library/xyter
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
  - name: semantic-release
    image: node:20
    commands:
      - echo "$DEPLOY_KEY" > /tmp/git_deploy_key
      - echo >> /tmp/git_deploy_key
      - chmod 600 /tmp/git_deploy_key
      - mkdir -p $HOME/.ssh
      - ssh-keyscan git.zyner.org > $HOME/.ssh/known_hosts
      - eval "$(ssh-agent -s)"
      - ssh-add /tmp/git_deploy_key
      - npm install
      - npx semantic-release
    environment:
      DEPLOY_KEY:
        from_secret: deploy-key
