version: "3.7"

services:
  app:
    container_name: app
    image: vermiumwastaken/xyter
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/logs
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Europe/Stockholm
      - MYSQL_DATABASE=test #optional
      - MYSQL_USER=test #optional
      - MYSQL_PASSWORD=test #optional
    volumes:
      - ./db:/config
    ports:
      - 3306:3306
    restart: unless-stopped
