version: "3.7"

services:
  xyter:
    container_name: xyter
    image: zyner/xyter:main
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/logs
    depends_on:
      - mariadb

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Region/City
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - ./db:/config
