version: "3.7"

services:
  app:
    container_name: app
    image: vermiumwastaken/xyter
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/logs

  mariadb:
    container_name: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Region/City
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - ./db:/config
    ports:
      - 3306:3306
